package a1;

public enum GamePiece {
	NONE, 
	HUMAN_KING, 
	HUMAN_NINJA, 
	HUMAN_SAMURAI, 
	HUMAN_MINI_NINJA, 
	HUMAN_MINI_SAMURAI, 
	COMPUTER_KING, 
	COMPUTER_NINJA,
	COMPUTER_SAMURAI, 
	COMPUTER_MINI_NINJA, 
	COMPUTER_MINI_SAMURAI
}
